### ISSUE TITLE
Better Game Badges - "100% Complete" circular badge not showing up

### ISSUE THREAD

**Issue by karasuhebi** [rasitayaz/steam-deck-themes#3]
The badge is not showing up. Worst yet, if you have "Library Move Extra Info" enabled, it hides that 100% complete badge as well.
![7_20230831013342_1](https://github.com/rasitayaz/steam-deck-themes/assets/6857825/f214c915-d6ef-4004-bd97-eb05859eb57f)
![7_20230831013334_1](https://github.com/rasitayaz/steam-deck-themes/assets/6857825/b9428d39-2134-42a7-9c29-48beb6b4a5d2)
![7_20230831013322_1](https://github.com/rasitayaz/steam-deck-themes/assets/6857825/477fb7b1-068b-42d7-870c-8acb8f62ea88)
![7_20230831013314_1](https://github.com/rasitayaz/steam-deck-themes/assets/6857825/cb29fab2-139d-4b4a-beef-1e67c3c4bc63)

**Comment by rasitayaz** [comment]
I edited fully completed badge to show up only when the game is highlighted, just like compatibility icons. Do they appear when you highlight the games?

**Comment by karasuhebi** [comment]
They don't appear when hovering a game either, no.

**Comment by rasitayaz** [comment]
did you try enabling "better game badges" only and disabling the rest?

**Comment by karasuhebi** [comment]
I just turned off ALL of my CSS Loader themes except for Better Game Badges and the badge does not show up when I hover on a game still.

**Comment by rasitayaz** [comment]
that's weird, which channel are you on? stable/beta/main?

**Comment by karasuhebi** [comment]
Stable

**Comment by rasitayaz** [comment]
alright going to look into this when I get the chance, at worst, I might add an option to display the badge all the time instead of just hover/highlight.

* in the meantime, can you also try hovering over capsules with mouse? (you can hold steam button down and use the right trackpad as mouse).
* please also check if you can see "in library" badges at "what's new" tab under recent games. (turn the theme off first to see if you have any game under "trending among friends" that you have in library) this badge should also appear when the game is highlighted or hovered.
