### ISSUE TITLE
[Question] 100% Badge Overlapping Download Status

### ISSUE THREAD

**Issue by ManedCalico** [rasitayaz/steam-deck-themes#4]
Hey rasitayaz!

I just downloaded the update for Better Game Badges-- very nicely done! I love all the options you've added!

I know you've also been working on Tormak's Download Status, and are a few commits ahead of the main branch. I was wondering if a fix for the 100% badge overlapping the download status icon will be part of your next pull request?

I've been tweaking that theme on the side for my own use, but I'd like to avoid the effort if it's something you already fixed.

Thanks!

**Comment by rasitayaz** [comment]
I think you're referring to the 'uninstalled' icon, because 'ready to play' icon in tormak's theme is already not visible when sorted by achievement completion.

I couldn't find a way to hide 'uninstalled' icons when sorted by achievement completion unfortunately. but I noticed that my 'all achieved' badges are not positioned the same as the 'uninstalled' badges, so I'll be fixing that to make the overlap less noticable.

for now, you can try the 'no uninstall' variant of 'show download status'.

**Comment by rasitayaz** [comment]
@ManedCalico latest version is published, all achieved badges now should be aligned with the download status badges, however, they are still slightly noticable when the badges are fading in and out.

**Comment by ManedCalico** [comment]
I just checked it out, and it's looking great! Thank you!
